DROP TABLE MVC_MEMBER;
CREATE TABLE MVC_MEMBER(
    mID VARCHAR2(30) PRIMARY KEY,
    mPW VARCHAR2(30) NOT NULL,
    mNAME VARCHAR2(30) NOT NULL,
    mEMAIL VARCHAR2(30),
    mPHOTO VARCHAR2(30) NOT NULL,
    mBIRTH DATE,
    mADDRESS VARCHAR2(300),
    mRDATE DATE DEFAULT SYSDATE NOT NULL
);
SELECT * FROM MVC_MEMBER;
-- DUMMY DATA
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS, MRDATE)
    VALUES ('a', 'a', '홍', 'a@a.com', 'default.png', '1999-01-01', '서울', '2000-12-12');
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS, MRDATE)
    VALUES ('b', 'b', '김', 'b@b.com', 'default.png', '1999-01-01', '서울', '2000-12-12');

-- DAO에 들어갈 QUERY
    -- 1. ID중복체크
SELECT COUNT(*) FROM MVC_MEMBER WHERE MID = 'c';
    -- 2. JOIN
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS, MRDATE)
    VALUES ('c', 'c', '이', 'a@a.com', 'default.png', '1999-01-01', '서울', '2000-12-12');
    -- 3. LOGIN CHECK
SELECT * FROM MVC_MEMBER WHERE MID = 'a' AND MPW = 'a';
    -- 4. mID로 MemberDto 가져오기
SELECT * FROM MVC_MEMBER WHERE MID = 'a';
COMMIT;