-- 예시
DROP TABLE BOOK;
DROP TABLE BOOKCATEGORY;
CREATE TABLE BOOKCATEGORY(
    CATEGORY_CODE NUMBER(3) PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) UNIQUE NOT NULL,
    OFFICE_LOC    VARCHAR2(50) NOT NULL
);
CREATE TABLE BOOK(
    BOOK_ID    VARCHAR2(30) PRIMARY KEY,
    -- BOOKCATEGORY 테이블에서는 PRIMARY KEY이지만 외래키로 받아온 BOOK 테이블에서는 NULL 가능
    CATEGORY_CODE NUMBER(3) REFERENCES BOOKCATEGORY(CATEGORY_CODE),
    BOOK_TITLE VARCHAR2(100) NOT NULL,
    BOOK_PRICE NUMBER(6) NOT NULL,
    BOOK_COUNT NUMBER(4) NOT NULL,
    AUTHOR     VARCHAR2(30) NOT NULL,
    PUBLISHING VARCHAR2(30) NOT NULL,
    BOOK_IMAGE1 VARCHAR2(100) DEFAULT 'onImg.png' NOT NULL,   -- 데이터베이스에 파일 이름만 저장된다
    BOOK_IMAGE2 VARCHAR2(100) DEFAULT 'NOTHING.JPG' NOT NULL,
    BOOK_DISCOUNT NUMBER(3) DEFAULT 0,
    BOOK_RDATE DATE DEFAULT SYSDATE NOT NULL
);

DROP TABLE BOOK;
DROP TABLE BOOKCATEGORY;

-- CH14_FILEUP BOOK 예제
DROP TABLE BOOK;
DROP SEQUENCE BOOK_SEQ;
CREATE TABLE BOOK(
    bID       NUMBER(7)     PRIMARY KEY,
    bTITLE    VARCHAR2(100) NOT NULL,   -- 책이름
    bPRICE    NUMBER(6)     NOT NULL,   -- 책가격
    bIMAGE1   VARCHAR2(100) NOT NULL,   -- 책 대표 이미지
    bIMAGE2   VARCHAR2(100) NOT NULL,   -- 책 추가 이미지
    bCONTENT  VARCHAR2(4000),           -- 책 설명(varchar2는 4000이 최대, 그 이상은 CLOB)
    bDISCOUNT NUMBER(3)     NOT NULL,   -- 할인율
    bRDATE    DATE DEFAULT SYSDATE NOT NULL   
);
CREATE SEQUENCE BOOK_SEQ
    MAXVALUE 9999999
    NOCACHE NOCYCLE;
SELECT * FROM BOOK;
-- 책등록
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT) 
    VALUES (BOOK_SEQ.NEXTVAL, '자바', 20000, 'noImg.png', 'NOTHING.JPG', 'CODING', 10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT) 
    VALUES (BOOK_SEQ.NEXTVAL, '내일의 부', 21000, '100.jpg', 'NOTHING.JPG', '부', 15);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT) 
    VALUES (BOOK_SEQ.NEXTVAL, '사슴', 22000, '103.jpg', 'NOTHING.JPG', '사슴', 5);
    
-- 책 리스트(PAGING 없이)
SELECT * FROM BOOK ORDER BY bRDATE DESC;    -- 최근 등록 순

-- 책 리스트(PAGING 추가 TOPN)
SELECT * FROM
    (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY bRDATE DESC) A)
    WHERE RN BETWEEN 2 AND 3;

-- 등록된 책 개수
SELECT COUNT(*) FROM BOOK;

-- 상세보기 (bID로 책 정보 가져오기)
SELECT * FROM BOOK WHERE bID = 2;
COMMIT;