-- Supermarket
DROP TABLE CUSTOMER;
DROP TABLE LEVELS;
DROP SEQUENCE CUSTOMER_CID_SQ;

CREATE TABLE LEVELS (
    LEVELNO NUMBER(3) PRIMARY KEY,
    LEVELNAME VARCHAR2(10) NOT NULL
);

CREATE TABLE CUSTOMER (
    CID NUMBER(5) PRIMARY KEY,
    CTEL VARCHAR2(50) NOT NULL,
    CNAME VARCHAR2(20) NOT NULL,
    CPOINT NUMBER(8),
    CAMOUNT NUMBER(9),
    LEVELUP NUMBER(9),
    LEVELNO NUMBER(3) REFERENCES LEVELS(LEVELNO),
    CHECK(CPOINT>=0),
    CHECK(CAMOUNT>=0)
);

CREATE SEQUENCE CUSTOMER_CID_SQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO LEVELS VALUES (1, 'NORMAL');
INSERT INTO LEVELS VALUES (2, 'SILVER');
INSERT INTO LEVELS VALUES (3, 'GOLD');
INSERT INTO LEVELS VALUES (4, 'VIP');
INSERT INTO LEVELS VALUES (5, 'VVIP');

-- ¥ıπÃµ•¿Ã≈Õ
INSERT INTO CUSTOMER (CID, CTEL, CNAME, CAMOUNT)
    VALUES (CUSTOMER_CID_SQ.NEXTVAL, '010-3333-3333', '»Ô∫Œ', 100000);
INSERT INTO CUSTOMER (CID, CTEL, CNAME, CAMOUNT)
    VALUES (CUSTOMER_CID_SQ.NEXTVAL, '010-3333-9999', '≥Ó∫Œ', 10000000);
    
SELECT * FROM LEVELS;
SELECT * FROM CUSTOMER;
COMMIT;