-- [XII] Transaction : COMMIT(트랜잭션 반영), ROLLBACK(트랜잭션 취소), SAVEPOINT(트랜잭션 분할)
-- COMMIT 시 : 새로운 트랜잭션 시작
-- ROLLBACK 시 : 전 트랜잭션으로 감
-- SAVEPOINT 세이브포인트명 : 현 시점을 세이브포인트로 지정
-- ROLLBACK TO SAVEPOINT명; : SAVEPOINT로 돌아간다

DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
COMMIT;
-------------------------- 새로운 트랜잭션 시작
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO=20;
DELETE FROM DEPT01 WHERE DEPTNO=30; 
ROLLBACK;
-------------------------- 새로운 트랜잭션 시작
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO=40;     
COMMIT;
-------------------------- 새로운 트랜잭션 시작
SELECT * FROM DEPT01; -- 10,20,30
DELETE FROM DEPT01 WHERE DEPTNO=30;
SELECT * FROM DEPT01; -- 10, 20
SAVEPOINT c1;   -- c1 시점 : 10, 20
DELETE FROM DEPT01 WHERE DEPTNO=20;
SELECT * FROM DEPT01;   -- 10
SAVEPOINT c2;   -- c2 시점 : 10
DELETE FROM DEPT01 WHERE DEPTNO=10;
SELECT * FROM DEPT01;
ROLLBACK TO c2;     -- c2로 돌아감
SELECT * FROM DEPT01;
ROLLBACK TO c1;
SELECT * FROM DEPT01;
COMMIT;
