DROP TABLE ORDERDETAIL;
DROP TABLE CART;
DROP TABLE ORDERS;
DROP TABLE PRODUCT;
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    mID VARCHAR2(20) PRIMARY KEY,
    mNAME VARCHAR2(40) NOT NULL,
    mADDR VARCHAR2(255),
    mTEL VARCHAR2(30),
    mEMAIL VARCHAR2(250) NOT NULL,
    UNIQUE(mEMAIL)
);

CREATE TABLE PRODUCT (
    pCODE VARCHAR2(250) PRIMARY KEY,
    pNAME VARCHAR2(250) NOT NULL,
    pPRICE NUMBER(6) NOT NULL,
    pSTOCK NUMBER(3) NOT NULL,
    CHECK(pPRICE>=0),
    CHECK(pSTOCK>=0)
);
DROP SEQUENCE CART_SEQ;
CREATE SEQUENCE CART_SEQ MAXVALUE 999999 NOCACHE;
CREATE TABLE CART (
    cNO NUMBER(6) PRIMARY KEY,
    mID VARCHAR2(20)  REFERENCES MEMBER(mID) NOT NULL,
    pCODE VARCHAR2(250) REFERENCES PRODUCT(pCODE) NOT NULL,
    QTY NUMBER(4) NOT NULL CHECK(QTY>=0),
    COST NUMBER(10) NOT NULL CHECK(COST>=0)
);

DROP SEQUENCE ORDERS_SEQ;
CREATE SEQUENCE ORDERS_SEQ MAXVALUE 999 NOCACHE;
CREATE TABLE ORDERS (
    oNO NUMBER(5) PRIMARY KEY,
    mID VARCHAR2(20) REFERENCES MEMBER(mID) NOT NULL,
    oNAME VARCHAR2(40) NOT NULL,
    oADDR VARCHAR2(250) NOT NULL,
    oTEL VARCHAR2(50) NOT NULL,
    oDATE DATE DEFAULT SYSDATE NOT NULL
);

DROP SEQUENCE ORDER_DETAIL_SEQ;
CREATE SEQUENCE ORDER_DETAIL_SEQ MAXVALUE 999999 NOCYCLE NOCACHE;
CREATE TABLE ORDER_DETAIL (
    odNO NUMBER(6) PRIMARY KEY,
    oNO NUMBER(3) REFERENCES ORDERS(oNO) NOT NULL,
    pCODE VARCHAR2(250) REFERENCES PRODUCT(pCODE) NOT NULL,
    QTY NUMBER(4) NOT NULL,
    COST NUMBER(10) NOT NULL,
    CHECK(QTY>=0),
    CHECK(COST>=0)
);

SELECT * FROM MEMBER;
SELECT * FROM PRODUCT;
SELECT * FROM CART;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAIL;
INSERT INTO 
    MEMBER VALUES ('abc','홍길동','서울 서대문구','010-9999-9999','hong@hong.com');
INSERT INTO 
    MEMBER VALUES ('def','김김동','경기도 수원시','010-8888-8888','kim@kim.com');
INSERT INTO PRODUCT VALUES ('A1', '맥주', 3000, 200);
INSERT INTO PRODUCT VALUES ('A2', '마스크', 200, 500);
INSERT INTO PRODUCT VALUES ('B1', '땅콩', 3000, 200);
INSERT INTO PRODUCT VALUES ('B2', '오징어', 5000, 200);
INSERT INTO PRODUCT VALUES ('C1', '소독약', 7000, 200);

SELECT TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.NEXTVAL, '000')) oNO FROM DUAL;
DROP SEQUENCE ORDERS_SEQ;
CREATE SEQUENCE ORDERS_SEQ MAXVALUE 999 NOCACHE;

-- 홍길동 주문서
INSERT INTO CART VALUES 
    (CART_SEQ.NEXTVAL, 'abc', 'A1', 3, (select pPRICE from product where pcode='A1')*3);
INSERT INTO CART VALUES 
    (CART_SEQ.NEXTVAL, 'abc', 'B1', 1, (SELECT pPRICE FROM PRODUCT WHERE pCODE='B1'));
SELECT * FROM CART;
SELECT 
     ORDER_DETAIL_SEQ.NEXTVAL odNO, 
        TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.CURRVAL, '000')) ono, 
        pcode, qty, cost 
    FROM CART WHERE MID='abc';
    
INSERT INTO ORDERS (ONO, MID, ONAME, OADDR, OTEL)
    VALUES (TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.NEXTVAL, '000')),
            'abc', '홍길동', '서울시 서대문구', '010-9999-9999');
-- ORDER_DETAIL(주문상세) 테이블
INSERT INTO ORDER_DETAIL (odNO, oNO, pCODE, QTY, COST)
    SELECT ORDER_DETAIL_SEQ.NEXTVAL, 
        TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.CURRVAL, '000')) ono, 
        pcode, qty, cost 
    FROM CART  WHERE MID='abc'; -- 서브쿼리 이용하여 장바구니의 모든 상품을 주문할 경우
-- 아래는 서브쿼리를 이용하지 않고 일부 상품만 구매할 경우 따로 따로 입력
-- A1, 맥주, 3000, 3개
INSERT INTO ORDER_DETAIL (odNO, oNO, pCODE, QTY, COST)
    VALUES (ORDER_DETAIL_SEQ.NEXTVAL,
        TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.CURRVAL, '000')),
        'A1',
        3,
        (SELECT pPRICE FROM PRODUCT WHERE pCODE='A1')*3);
UPDATE PRODUCT SET pSTOCK = pSTOCK-3 WHERE pCODE='A1'; -- 재고 수량 수정
-- B1, 땅콩, 3000, 1개
INSERT INTO ORDER_DETAIL (odNO, oNO, pCODE, QTY, COST)
    VALUES
    (ORDER_DETAIL_SEQ.NEXTVAL, 
    TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.CURRVAL, '000')), 
    'B1',
    1, 
    (SELECT pPRICE FROM PRODUCT WHERE pCODE='B1')*1);
UPDATE PRODUCT SET pSTOCK = pSTOCK-1 WHERE pCODE='B1';-- 재고 수량 수정
DELETE FROM CART WHERE MID='abc';-- 장바구니 비우기

-- 주문서에 필요한 데이터 출력
--현재 주문번호만 SELECT절에 현재 시퀀스값을 이용하여 가져올 수 있으나 시퀀스.CURRVAL은 WHERE절에서 사용할 수 없음
SELECT TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.CURRVAL, '000')) FROM DUAL; 

SELECT * FROM ORDERS WHERE ONO=230102002;

SELECT O.PCODE, PNAME, pPRICE, QTY, COST
    FROM ORDER_DETAIL O, PRODUCT P
    WHERE O.PCODE=P.PCODE AND
        ONO=230102002;