-- ★ 연습문제(PDF4) ★
DROP TABLE BOOK;
CREATE TABLE BOOKCATEGORY(
    CATEGORYCODE NUMBER(4) PRIMARY KEY,
    CATEGORYNAME VARCHAR2(50) UNIQUE,
    OFFICE_LOC VARCHAR2(50) NOT NULL
);
INSERT INTO BOOKCATEGORY 
    VALUES (100, '철학', '3층 인문실');
INSERT INTO BOOKCATEGORY 
    VALUES (200, '인문', '3층 인문실');
INSERT INTO BOOKCATEGORY 
    VALUES (300, '자연과학', '4층 과학실');
INSERT INTO BOOKCATEGORY 
    VALUES (400, 'IT', '4층 과학실');
SELECT * FROM BOOKCATEGORY;
DROP TABLE BOOKCATEGORY;

CREATE TABLE BOOK(
    이ㅣCATEGORYCODE NUMBER(4),
    bookNO VARCHAR2(50),
    bookNAME VARCHAR2(50),
    PUBLISHER VARCHAR2(50),
    PUBYEAR NUMBER(4) DEFAULT TO_CHAR(SYSDATE, 'YYYY'),
    FOREIGN KEY(CATEGORYCODE) REFERENCES BOOKCATEGORY(CATEGORYCODE),
    PRIMARY KEY(bookNO)
);
SELECT * FROM BOOK;
INSERT INTO BOOK VALUES (100, '100A01', '철학자의 삶', '이젠출판', 2021);
INSERT INTO BOOK VALUES (400, '400A01', '이것이DB다', '다음출판', 2022);


-- 연습문제 2
DROP TABLE STUDENT;
DROP TABLE MAJOR;


CREATE TABLE MAJOR (
    MAJOR_CODE NUMBER(2) PRIMARY KEY,
    MAJOR_NAME VARCHAR2(50), 
    major_OFFICE_LOC VARCHAR2(200)
);
INSERT INTO MAJOR VALUES (1, '컴퓨터공학', 'A101호');
INSERT INTO MAJOR VALUES (2, '빅데이터', 'A102호');
SELECT * FROM MAJOR;

CREATE TABLE STUDENT(
    student_code NUMBER(4) PRIMARY KEY,
    student_NAME VARCHAR2(20),
    SCORE NUMBER(3),
    MAJOR_CODE NUMBER(2),
    FOREIGN KEY(MAJOR_CODE) REFERENCES MAJOR(MAJOR_CODE),
    CHECK(0<=SCORE AND SCORE<=100)
);
INSERT INTO STUDENT VALUES (101, '홍길동', 99, 1);
INSERT INTO STUDENT VALUES (102, '신길동', 100, 2);
SELECT * FROM STUDENT;

SELECT S.*, M.* 
    FROM STUDENT S, MAJOR M 
    WHERE S.MAJOR_CODE=M.MAJOR_CODE
    ORDER BY S.MAJOR_CODE;