-- 테이블 생성 & 더미데이터
-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE pNO_SEQ;
-- 테이블 및 시퀀스 생성
CREATE TABLE JOB (  -- JOB
    jNO NUMBER(2) PRIMARY KEY,
    jNAME VARCHAR2(50)
);
CREATE TABLE PERSON (   -- PERSON
    pNO NUMBER(5) PRIMARY KEY,
    pNAME VARCHAR2(50) NOT NULL,
    jNO NUMBER(2) REFERENCES JOB(jNO),
    KOR NUMBER(3)CHECK(KOR>=0),
    ENG NUMBER(3)CHECK(ENG>=0),
    MAT NUMBER(3)CHECK(MAT>=0)  
);
DROP SEQUENCE pNO_SEQ;
    CREATE SEQUENCE pNO_SEQ MAXVALUE 99999 NOCACHE;  -- pNO_SEQ

-- 더미데이터 insert
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');  -- JOB
INSERT INTO PERSON VALUES (pNO_SEQ.NEXTVAL, '정우성', 10, 90, 80, 81); 
INSERT INTO PERSON VALUES (pNO_SEQ.NEXTVAL, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES (pNO_SEQ.NEXTVAL, '배수지', 20, 20, 90, 90);
INSERT INTO PERSON VALUES (pNO_SEQ.NEXTVAL, '설수현', 20, 95, 95, 95);
INSERT INTO PERSON VALUES (pNO_SEQ.NEXTVAL, '송혜교', 10, 100, 100, 100);
SELECT * FROM JOB;
SELECT * FROM PERSON;
COMMIT;