DROP TABLE BOARD;
CREATE TABLE BOARD(
    NUM NUMBER(5, 0) PRIMARY KEY,
    WRITER VARCHAR2(30) NOT NULL,
    SUBJECT VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(30),
    READCOUNT NUMBER(5) DEFAULT 0,
    PW VARCHAR2(30) NOT NULL,
    REF NUMBER(5, 0) NOT NULL,
    REF_STEP NUMBER(3) NOT NULL,
    REF_INDENT NUMBER(3) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    RDATE DATE DEFAULT SYSDATE
);
SELECT * FROM BOARD;

-- 1. 글 개수
SELECT COUNT(*) FROM BOARD;

-- 2. 글 목록(최신순)
SELECT * FROM BOARD ORDER BY REF DESC;

-- 2. 글목록 (TOPN구문)
SELECT *   
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY REF DESC) A)
    WHERE RN BETWEEN 1 AND 10;

-- 3. 원글 쓰기
INSERT INTO BOARD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, REF_STEP, REF_INDENT, IP)
    VALUES ((SELECT NVL(MAX(NUM), 0)+1 FROM BOARD), 'aasdf', '제목', '본문', NULL, '111', 
            (SELECT NVL(MAX(NUM), 0)+1 FROM BOARD), 0, 0, '0,0,0,0');
            
-- 4. 글번호로 글 상세내용 보기
SELECT * FROM BOARD WHERE NUM=1;

-- 5. 조회수 올리기
UPDATE BOARD SET READCOUNT = READCOUNT + 1 WHERE NUM = 1;

-- 6. 글 수정
UPDATE BOARD SET SUBJECT = '제목 수정',
                 CONTENT = '내용 수정',
                 EMAIL = 'ASD@A.A',
                 PW = '111'
            WHERE NUM = 1;
            
-- 7. 글삭제
COMMIT;
DELETE FROM BOARD WHERE NUM=1 AND PW='111';
ROLLBACK;
                 
SELECT * FROM BOARD;