-- FRIEND 테이블 생성
DROP TABLE FRIEND;
CREATE TABLE FRIEND (
        NO NUMBER(4) PRIMARY KEY,
        NAME VARCHAR2(20) NOT NULL,
        TEL VARCHAR2(20)
);
SELECT * FROM FRIEND;

-- 시퀀스 FRIEND_NO_SEQ : 1부터 하나씩 증가하는 시퀀스
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ MAXVALUE 9999 NOCACHE;

-- 친구 추가
INSERT INTO FRIEND (NO, NAME, TEL)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999');
    
-- 친구 목록 출력
SELECT * FROM FRIEND;

-- 친구 검색
SELECT * FROM FRIEND WHERE NAME LIKE '%'||'김'||'%' AND TEL LIKE '%'||''||'%';
COMMIT;


