DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_NO_SQ;
CREATE TABLE MEMBER(
  NO NUMBER(3) PRIMARY KEY,
  NAME VARCHAR2(30) UNIQUE NOT NULL,
  TEL VARCHAR2(30)
);
CREATE SEQUENCE MEMBER_NO_SQ MAXVALUE 999 NOCACHE NOCYCLE;
INSERT INTO MEMBER VALUES (MEMBER_NO_SQ.NEXTVAL, '홍길동', '010-9999-9999');
SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE NO=1;
SELECT * FROM MEMBER WHERE NAME='홍길동';
COMMIT;